# Generated by Django 6.1 on 2026-08-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobsapplicationmodel_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsapplicationmodel',
            name='applied_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
