# Generated by Django 6.1 on 2026-09-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobsapplicationmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsapplicationmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
