# Generated by Django 6.1 on 2026-09-17 17:12

import apps.jobs.models.job_applications
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobsapplicationmodel_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsapplicationmodel',
            options={'verbose_name': 'Bewerbung', 'verbose_name_plural': 'Bewerbungen'},
        ),
        migrations.AlterField(
            model_name='jobsapplicationmodel',
            name='applied_at',
            field=models.DateField(blank=True, error_messages={'invalid': 'Bitte gib ein gültiges Datum ein (Format: JJJJ-MM-TT).'}, help_text='Datum, an dem die Bewerbung abgeschickt wurde.', null=True, validators=[apps.jobs.models.job_applications.validate_not_in_future], verbose_name='Bewerbungsdatum'),
        ),
        migrations.AlterField(
            model_name='jobsapplicationmodel',
            name='company_name',
            field=models.CharField(error_messages={'blank': 'Bitte gib den Firmennamen ein.', 'max_length': 'Der Firmenname darf maximal 255 Zeichen lang sein.'}, help_text='Name des Unternehmens, bei dem du dich beworben hast.', max_length=255, verbose_name='Firmenname'),
        ),
        migrations.AlterField(
            model_name='jobsapplicationmodel',
            name='description',
            field=models.TextField(error_messages={'blank': 'Bitte gib eine Beschreibung ein.'}, help_text='Beschreibung der Position oder Bewerbung.', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='jobsapplicationmodel',
            name='notes',
            field=models.TextField(blank=True, help_text='Optionale persönliche Notizen zur Bewerbung.', null=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='jobsapplicationmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt')], default='pending', error_messages={'invalid_choice': 'Ungültiger Status ausgewählt.'}, help_text='Aktueller Stand der Bewerbung.', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobsapplicationmodel',
            name='url',
            field=models.TextField(blank=True, help_text='Optionaler Link zur Stellenausschreibung.', null=True, verbose_name='Link zur Stellenanzeige'),
        ),
    ]
